// TypeScript-converted inline script; DOM/UI behavior intentionally preserved.
// @ts-nocheck
function getDefaultBlogs() { return [{ title: "How to Choose Right GSM Bubble Wrap for E-commerce?", content: "For mobile and electronics, use 40-50 GSM small bubble. For heavy items like furniture, use 80-120 GSM large bubble. Always check width 0.5m to 1.5m as per product size. As a wholesaler, we keep all GSM in ready stock.\n\nWe purchase in bulk from factories and supply at wholesale rates PAN India.", img: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600", date: "2024-01-15" }, { title: "5 Packing Tips to Reduce Courier Damage", content: "1. Use double layer bubble wrap for fragile items.\n2. Fill empty space with bubble wrap to prevent movement.\n3. Use BOPP tape properly for sealing.\n4. Use corrugated carton outside for extra protection.\n5. Buy from wholesaler for best quality at low price.\n\nFollow these tips and reduce damage by 90%.", img: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600", date: "2024-02-10" }, { title: "Why Buying From Wholesaler Is Better Than Factory?", content: "Factories have high MOQ 50-100 rolls and waiting time 3-5 days. They also charge extra for small orders.\n\nWholesaler like A.J TRADERS gives you from 1 roll, same day dispatch, PAN India delivery, GST invoice, and best wholesale rates. We maintain ready stock in Faridabad godown.", img: "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=600", date: "2024-03-05" }]; }
function localEsc(v) { return String(v == null ? '' : v).replace(/[&<>'"]/g, function (c) { if (c === '&')
    return '&amp;'; if (c === '<')
    return '&lt;'; if (c === '>')
    return '&gt;'; if (c === "'")
    return '&#39;'; return '&quot;'; }); }
function loadBlogs() { var E = (window.AJShared && AJShared.escapeHTML) ? AJShared.escapeHTML : localEsc; var s = localStorage.getItem('aj_blogs'); var blogs = s ? JSON.parse(s) : getDefaultBlogs(); if (!s)
    localStorage.setItem('aj_blogs', JSON.stringify(blogs)); var grid = document.getElementById('blogGrid'); grid.innerHTML = blogs.map(function (b, i) { return '<div class="glass rounded-3xl overflow-hidden cursor-pointer hover:border-[#D4AF37]/40 transition" onclick="openBlog(' + i + ')"><div class="h-48 bg-slate-950 overflow-hidden"><img src="' + b.img + '" alt="' + b.title + '" loading="lazy" class="w-full h-full object-cover"></div><div class="p-5"><div class="text-[10px] text-[#D4AF37] font-bold">' + E(b.date) + '</div><h3 class="font-bold text-sm mt-2 leading-tight">' + E(b.title) + '</h3><p class="text-[11px] text-slate-400 mt-2 line-clamp-3">' + E(b.content.substring(0, 120)) + '...</p><span class="inline-block mt-4 text-[11px] text-[#D4AF37] font-bold">Read More →</span></div></div>'; }).join(''); }
function openBlog(i) { var s = localStorage.getItem('aj_blogs'); var blogs = s ? JSON.parse(s) : getDefaultBlogs(); var b = blogs[i]; document.getElementById('modalBlogImg').src = b.img; document.getElementById('modalBlogTitle').textContent = b.title; document.getElementById('modalBlogDate').textContent = b.date; document.getElementById('modalBlogContent').textContent = b.content; document.getElementById('blogModal').classList.remove('hidden'); document.getElementById('blogModal').classList.add('flex'); }
function closeBlogModal() { document.getElementById('blogModal').classList.add('hidden'); document.getElementById('blogModal').classList.remove('flex'); }
document.addEventListener('DOMContentLoaded', loadBlogs);
window.addEventListener('aj:data-updated', loadBlogs);
