// TypeScript-converted inline script; DOM/UI behavior intentionally preserved.
// @ts-nocheck
function getDefaultTestimonials() { return [{ name: "Rahul Sharma", company: "E-commerce Seller, Delhi", review: "Best wholesale bubble wrap supplier in Faridabad. Same day dispatch and genuine wholesale rates. Quality is checked properly.", img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200" }, { name: "Priya Enterprises", company: "Amazon Seller, Gurgaon", review: "Quality is top notch. GSM checked properly. 5000+ clients trust is real. We have been buying from last 2 years.", img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200" }, { name: "Amit Traders", company: "Wholesaler, Mumbai", review: "PAN India delivery in 2-3 days. Very professional wholesaler, not a factory. Low MOQ helped our startup.", img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200" }, { name: "Delhi Packers", company: "Packaging Company, Faridabad", review: "Ready stock always available. No factory waiting time. Best rates in NCR.", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200" }, { name: "Ecom Solutions", company: "Flipkart Seller, Noida", review: "BOPP tapes and cartons also available at wholesale rates. One stop solution for packaging.", img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200" }, { name: "Gurgaon Logistics", company: "Logistics, Gurgaon", review: "Same day dispatch is real. Ordered 50 rolls 1.2m at 11 AM, dispatched same day at 3 PM with tracking.", img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200" }]; }
function localEsc(v) { return String(v == null ? '' : v).replace(/[&<>'"]/g, function (c) { if (c === '&')
    return '&amp;'; if (c === '<')
    return '&lt;'; if (c === '>')
    return '&gt;'; if (c === "'")
    return '&#39;'; return '&quot;'; }); }
function loadTestimonials() { var E = (window.AJShared && AJShared.escapeHTML) ? AJShared.escapeHTML : localEsc; var s = localStorage.getItem('aj_testimonials'); var testimonials = s ? JSON.parse(s) : getDefaultTestimonials(); if (!s)
    localStorage.setItem('aj_testimonials', JSON.stringify(testimonials)); var grid = document.getElementById('testimonialsGrid'); grid.innerHTML = testimonials.map(function (t) { return '<div class="glass p-6 rounded-3xl"><div class="flex items-center gap-4"><div class="w-14 h-14 rounded-full overflow-hidden bg-slate-900 border border-slate-700 shrink-0"><img src="' + E(t.img) + '" alt="' + E(t.name) + '" loading="lazy" class="w-full h-full object-cover"></div><div><div class="font-bold text-sm">' + E(t.name) + '</div><div class="text-[10px] text-[#D4AF37]">' + E(t.company) + '</div></div></div><div class="flex gap-1 mt-4 text-[#D4AF37] text-[10px]"><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></div><p class="text-xs text-slate-300 mt-3 leading-relaxed">\"' + E(t.review) + '\"</p></div>'; }).join(''); }
document.addEventListener('DOMContentLoaded', loadTestimonials);
window.addEventListener('aj:data-updated', loadTestimonials);
